require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::PropertiesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Property. As you add validations to Admin::Property, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::PropertiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_properties as @admin_properties" do
      property = Admin::Property.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_properties).should eq([property])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_property as @admin_property" do
      property = Admin::Property.create! valid_attributes
      get :show, {:id => property.to_param}, valid_session
      assigns(:admin_property).should eq(property)
    end
  end

  describe "GET new" do
    it "assigns a new admin_property as @admin_property" do
      get :new, {}, valid_session
      assigns(:admin_property).should be_a_new(Admin::Property)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_property as @admin_property" do
      property = Admin::Property.create! valid_attributes
      get :edit, {:id => property.to_param}, valid_session
      assigns(:admin_property).should eq(property)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Property" do
        expect {
          post :create, {:admin_property => valid_attributes}, valid_session
        }.to change(Admin::Property, :count).by(1)
      end

      it "assigns a newly created admin_property as @admin_property" do
        post :create, {:admin_property => valid_attributes}, valid_session
        assigns(:admin_property).should be_a(Admin::Property)
        assigns(:admin_property).should be_persisted
      end

      it "redirects to the created admin_property" do
        post :create, {:admin_property => valid_attributes}, valid_session
        response.should redirect_to(Admin::Property.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_property as @admin_property" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Property.any_instance.stub(:save).and_return(false)
        post :create, {:admin_property => {}}, valid_session
        assigns(:admin_property).should be_a_new(Admin::Property)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Property.any_instance.stub(:save).and_return(false)
        post :create, {:admin_property => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_property" do
        property = Admin::Property.create! valid_attributes
        # Assuming there are no other admin_properties in the database, this
        # specifies that the Admin::Property created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Property.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => property.to_param, :admin_property => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested admin_property as @admin_property" do
        property = Admin::Property.create! valid_attributes
        put :update, {:id => property.to_param, :admin_property => valid_attributes}, valid_session
        assigns(:admin_property).should eq(property)
      end

      it "redirects to the admin_property" do
        property = Admin::Property.create! valid_attributes
        put :update, {:id => property.to_param, :admin_property => valid_attributes}, valid_session
        response.should redirect_to(property)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_property as @admin_property" do
        property = Admin::Property.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Property.any_instance.stub(:save).and_return(false)
        put :update, {:id => property.to_param, :admin_property => {}}, valid_session
        assigns(:admin_property).should eq(property)
      end

      it "re-renders the 'edit' template" do
        property = Admin::Property.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Property.any_instance.stub(:save).and_return(false)
        put :update, {:id => property.to_param, :admin_property => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_property" do
      property = Admin::Property.create! valid_attributes
      expect {
        delete :destroy, {:id => property.to_param}, valid_session
      }.to change(Admin::Property, :count).by(-1)
    end

    it "redirects to the admin_properties list" do
      property = Admin::Property.create! valid_attributes
      delete :destroy, {:id => property.to_param}, valid_session
      response.should redirect_to(admin_properties_url)
    end
  end

end
