development:
  bucket: bdp-assets-development
  access_key_id: AKIAITWCJUBUVR5Y42TA
  secret_access_key: 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
  
test:
  bucket: bdp-assets-test
  access_key_id: AKIAITWCJUBUVR5Y42TA
  secret_access_key: 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
  
production:
  bucket: bdp-assets
  access_key_id: AKIAITWCJUBUVR5Y42TA
  secret_access_key: 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
